from pathlib import Path
import argparse, json, pickle, time
import numpy as np
from sklearn.datasets import load_breast_cancer, load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results"
GEN = ROOT / "generated"
OUT.mkdir(exist_ok=True)
GEN.mkdir(exist_ok=True)

DATASETS = {
    "breast_cancer": {
        "label": "Breast Cancer Wisconsin",
        "loader": load_breast_cancer,
        # TinyRISC v1 is a 4-input teaching CPU. Use four real features from the real dataset.
        "feature_indices": [0, 1, 2, 3],
    },
    "iris": {
        "label": "Iris",
        "loader": load_iris,
        "feature_indices": [0, 1, 2, 3],
    },
}


def load_dataset(name):
    cfg = DATASETS[name]
    ds = cfg["loader"]()
    fi = cfg["feature_indices"]
    X = ds.data[:, fi].astype(float)
    y = ds.target.astype(int)
    feature_names = [str(ds.feature_names[i]) for i in fi]
    class_names = [str(x) for x in ds.target_names]
    return X, y, feature_names, class_names, cfg["label"]


def sv_header(name, dataset):
    return f"// AUTO-GENERATED by python/train_models.py\n// Dataset: {dataset}\n// Model: {name}\n"


def sv_signed(v, bits=32):
    v = int(v)
    return f"{bits}'sd{v}" if v >= 0 else f"-{bits}'sd{abs(v)}"


def make_tb(module_name, expected, qx, pred_bits):
    assigns = "\n".join(f"    x{i} = {sv_signed(v,8)};" for i, v in enumerate(qx))
    return f"""module tb;
  logic signed [7:0] x0,x1,x2,x3;
  logic [{pred_bits-1}:0] prediction;
  {module_name} dut(.x0(x0),.x1(x1),.x2(x2),.x3(x3),.prediction(prediction));
  initial begin
{assigns}
    #1;
    $display("RESULT prediction=%0d expected={int(expected)}", prediction);
    if (prediction !== {pred_bits}'d{int(expected)}) $error("Prediction mismatch");
    $finish;
  end
endmodule
"""


def write_json(name, payload):
    (OUT / f"{name}.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


def quantize_matrix(W, target=90):
    scale = max(float(np.max(np.abs(W))) / float(target), 1e-9)
    return np.clip(np.round(W / scale), -127, 127).astype(int), scale


def train(dataset_name):
    X_raw, y, feature_names, class_names, dataset_label = load_dataset(dataset_name)
    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X_raw, y, test_size=0.30, random_state=7, stratify=y
    )
    scaler = StandardScaler().fit(X_train_raw)
    X_train = scaler.transform(X_train_raw)
    X_test = scaler.transform(X_test_raw)
    n_classes = int(len(np.unique(y)))
    pred_bits = max(1, int(np.ceil(np.log2(n_classes))))

    # Hardware input quantization uses one scale for all four standardized features.
    x_scale = max(float(np.max(np.abs(X_train))) / 100.0, 1e-9)
    Q_train = np.clip(np.round(X_train / x_scale), -127, 127).astype(int)
    Q_test = np.clip(np.round(X_test / x_scale), -127, 127).astype(int)
    sample = X_test[0]
    q_sample = Q_test[0]

    models = {}
    model_stats = {}

    # Logistic Regression
    t0 = time.perf_counter()
    log = LogisticRegression(max_iter=3000, random_state=7).fit(X_train, y_train)
    train_ms = (time.perf_counter() - t0) * 1000.0
    acc = accuracy_score(y_test, log.predict(X_test))
    models["logistic_regression"] = log
    model_stats["logistic_regression"] = {"accuracy": float(acc), "train_ms": train_ms}

    if n_classes == 2:
        W = log.coef_.reshape(1, -1)
        B = log.intercept_.reshape(1)
    else:
        W = log.coef_
        B = log.intercept_
    qW, w_scale = quantize_matrix(W)
    qB = np.round(B / (x_scale * w_scale)).astype(int)
    pred = int(log.predict(sample.reshape(1, -1))[0])
    score_lines=[]
    for c in range(len(qB)):
        terms = " + ".join(f"$signed(x{i}) * {sv_signed(qW[c,i])}" for i in range(4))
        score_lines.append(f"    score{c} = {terms} + {sv_signed(qB[c])};")
    if n_classes == 2:
        pred_logic = "    prediction = (score0 >= 0) ? 1 : 0;"
    else:
        # 3-class Iris only in this project.
        pred_logic = "    prediction = (score0 >= score1 && score0 >= score2) ? 0 : ((score1 >= score2) ? 1 : 2);"
    sv = sv_header("logistic_regression", dataset_label) + f"""module logistic_inference(
 input logic signed [7:0] x0,x1,x2,x3,
 output logic [{pred_bits-1}:0] prediction
);
"""
    for c in range(len(qB)): sv += f" logic signed [31:0] score{c};\n"
    sv += " always_comb begin\n" + "\n".join(score_lines) + "\n" + pred_logic + "\n end\nendmodule\n"
    (GEN / "logistic_inference.sv").write_text(sv)
    (GEN / "logistic_tb.sv").write_text(make_tb("logistic_inference", pred, q_sample, pred_bits))
    write_json("logistic_regression", {
        "model":"LogisticRegression", "dataset":dataset_name, "test_accuracy":float(acc), "input_scale":x_scale,
        "n_classes":n_classes, "class_names":class_names, "sample_int8":q_sample.tolist(), "sklearn_prediction":pred,
        "exported":{"weights_int8":qW.tolist(), "bias_int32":qB.tolist()},
        "hardware":"Class score dot products + argmax" if n_classes>2 else "Dot product + bias + sign compare"
    })

    # Decision Tree
    t0=time.perf_counter()
    tree=DecisionTreeClassifier(max_depth=4,min_samples_leaf=4,random_state=7).fit(X_train,y_train)
    train_ms=(time.perf_counter()-t0)*1000.0
    acc=accuracy_score(y_test,tree.predict(X_test))
    models["decision_tree"]=tree; model_stats["decision_tree"]={"accuracy":float(acc),"train_ms":train_ms}
    pred=int(tree.predict(sample.reshape(1,-1))[0]); tt=tree.tree_
    nodes=[]
    for i in range(tt.node_count):
        leaf=tt.children_left[i]==tt.children_right[i]
        nodes.append({"id":i,"leaf":bool(leaf),"feature":None if leaf else int(tt.feature[i]),
                      "threshold_int8":None if leaf else int(round(float(tt.threshold[i])/x_scale)),
                      "left":None if leaf else int(tt.children_left[i]),"right":None if leaf else int(tt.children_right[i]),
                      "class":int(np.argmax(tt.value[i][0])) if leaf else None})
    write_json("decision_tree", {"model":"DecisionTreeClassifier","dataset":dataset_name,"test_accuracy":float(acc),
        "input_scale":x_scale,"n_classes":n_classes,"class_names":class_names,"sample_int8":q_sample.tolist(),
        "sklearn_prediction":pred,"exported":{"nodes":nodes},"hardware":"Threshold compare + branch"})

    # Random Forest
    t0=time.perf_counter()
    forest=RandomForestClassifier(n_estimators=5,max_depth=4,min_samples_leaf=4,random_state=7).fit(X_train,y_train)
    train_ms=(time.perf_counter()-t0)*1000.0
    acc=accuracy_score(y_test,forest.predict(X_test))
    models["random_forest"]=forest; model_stats["random_forest"]={"accuracy":float(acc),"train_ms":train_ms}
    pred=int(forest.predict(sample.reshape(1,-1))[0])
    trees=[]
    for ti,est in enumerate(forest.estimators_):
        t=est.tree_; ns=[]
        for i in range(t.node_count):
            leaf=t.children_left[i]==t.children_right[i]
            ns.append({"id":i,"leaf":bool(leaf),"feature":None if leaf else int(t.feature[i]),
                       "threshold_int8":None if leaf else int(round(float(t.threshold[i])/x_scale)),
                       "left":None if leaf else int(t.children_left[i]),"right":None if leaf else int(t.children_right[i]),
                       "class":int(np.argmax(t.value[i][0])) if leaf else None})
        trees.append({"tree":ti,"nodes":ns})
    write_json("random_forest", {"model":"RandomForestClassifier","dataset":dataset_name,"test_accuracy":float(acc),
        "input_scale":x_scale,"n_classes":n_classes,"class_names":class_names,"sample_int8":q_sample.tolist(),
        "sklearn_prediction":pred,"exported":{"n_trees":len(trees),"trees":trees},"hardware":"Tree inference + class voting"})

    # MLP 4 -> 6 ReLU -> C (or one binary score)
    t0=time.perf_counter()
    mlp=MLPClassifier(hidden_layer_sizes=(6,),activation="relu",solver="adam",max_iter=3000,random_state=7).fit(X_train,y_train)
    train_ms=(time.perf_counter()-t0)*1000.0
    acc=accuracy_score(y_test,mlp.predict(X_test))
    models["mlp_classifier"]=mlp; model_stats["mlp_classifier"]={"accuracy":float(acc),"train_ms":train_ms}
    pred=int(mlp.predict(sample.reshape(1,-1))[0])
    W1=mlp.coefs_[0]; b1=mlp.intercepts_[0]
    qW1,w1_scale=quantize_matrix(W1)
    qb1=np.round(b1/(x_scale*w1_scale)).astype(int)
    hacc=Q_train@qW1+qb1; relu=np.maximum(hacc,0)
    max_relu=max(int(np.max(relu)),1)
    shift=max(0,int(np.ceil(np.log2(max_relu/100.0)))) if max_relu>100 else 0
    h_scale=x_scale*w1_scale*(2**shift)
    W2=mlp.coefs_[1]
    b2=mlp.intercepts_[1]
    qW2,w2_scale=quantize_matrix(W2)
    qb2=np.round(b2/(h_scale*w2_scale)).astype(int)
    write_json("mlp_classifier", {"model":"MLPClassifier","dataset":dataset_name,"test_accuracy":float(acc),
        "input_scale":x_scale,"n_classes":n_classes,"class_names":class_names,"sample_int8":q_sample.tolist(),
        "sklearn_prediction":pred,"exported":{"architecture":f"4 -> 6 ReLU -> {W2.shape[1]}",
        "w1_int8":qW1.tolist(),"b1_int32":qb1.tolist(),"hidden_shift":shift,
        "w2_int8":qW2.tolist(),"b2_int32":qb2.tolist()},"hardware":"Matrix multiply + ReLU + class argmax"})

    summary={
        "dataset": dataset_name,
        "dataset_label": dataset_label,
        "rows": int(len(X_raw)),
        "features_used": feature_names,
        "n_classes": n_classes,
        "class_names": class_names,
        "note": ("TinyRISC v1 uses four ML input features. Breast Cancer uses four real features: mean radius, mean texture, mean perimeter and mean area." if dataset_name == "breast_cancer" else "TinyRISC v1 uses all four original Iris features and supports 3-class inference."),
        "models": model_stats,
    }
    (OUT/"models_summary.json").write_text(json.dumps(summary,indent=2),encoding="utf-8")
    with (OUT/"training_artifacts.pkl").open("wb") as f:
        pickle.dump({"dataset":dataset_name,"X_train":X_train,"y_train":y_train,"X_test":X_test,"y_test":y_test,
                     "Q_train":Q_train,"Q_test":Q_test,"x_scale":x_scale,"scaler":scaler,"feature_names":feature_names,
                     "class_names":class_names,"n_classes":n_classes,"models":models},f)
    print(json.dumps(summary,indent=2))


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--dataset",choices=sorted(DATASETS),default="breast_cancer")
    args=ap.parse_args()
    train(args.dataset)

if __name__=="__main__": main()
