from pathlib import Path
import json
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "results"
GEN = ROOT / "generated"
OUT.mkdir(exist_ok=True)
GEN.mkdir(exist_ok=True)

X, y = make_classification(
    n_samples=800, n_features=4, n_informative=4, n_redundant=0,
    random_state=7, class_sep=1.5
)
x_scale = max(float(np.max(np.abs(X))) / 100.0, 1e-9)
QX = np.clip(np.round(X / x_scale), -127, 127).astype(int)
sample_idx = 0
sample = X[sample_idx]
q_sample = QX[sample_idx]


def sv_header(name):
    return f"// AUTO-GENERATED by python/train_models.py\n// Model: {name}\n"


def sv_int8(v):
    v = int(v)
    return f"8\'sd{v}" if v >= 0 else f"-8\'sd{abs(v)}"

def sv_i32(v):
    v = int(v)
    return f"32\'sd{v}" if v >= 0 else f"-32\'sd{abs(v)}"


def make_tb(module_name, expected, qx):
    assigns = "\n".join(f"    x{i} = {sv_int8(v)};" for i, v in enumerate(qx))
    return f"""module tb;
  logic signed [7:0] x0,x1,x2,x3;
  logic prediction;
  {module_name} dut(.x0(x0),.x1(x1),.x2(x2),.x3(x3),.prediction(prediction));
  initial begin
{assigns}
    #1;
    $display("RESULT prediction=%0d expected={int(expected)}", prediction);
    if (prediction !== 1'b{int(expected)}) $error("Prediction mismatch");
    $finish;
  end
endmodule
"""


def write_json(name, payload):
    (OUT / f"{name}.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")

# Logistic Regression
log = LogisticRegression(max_iter=2000, random_state=7).fit(X, y)
log_acc = accuracy_score(y, log.predict(X))
w = log.coef_[0]
w_scale = max(float(np.max(np.abs(w))) / 100.0, 1e-9)
qw = np.clip(np.round(w / w_scale), -127, 127).astype(int)
qb = int(round(float(log.intercept_[0]) / (x_scale * w_scale)))
log_pred = int(log.predict(sample.reshape(1, -1))[0])
terms = " + ".join(f"$signed(x{i}) * {sv_i32(qw[i])}" for i in range(4))
sv = sv_header("logistic_regression") + f"""module logistic_inference(
 input logic signed [7:0] x0,x1,x2,x3,
 output logic prediction
);
 logic signed [31:0] score;
 always_comb begin
   score = {terms} + {sv_i32(qb)};
   prediction = (score >= 0);
 end
endmodule
"""
(GEN / "logistic_inference.sv").write_text(sv)
(GEN / "logistic_tb.sv").write_text(make_tb("logistic_inference", log_pred, q_sample))
write_json("logistic_regression", {
    "model": "LogisticRegression", "train_accuracy": float(log_acc),
    "input_scale": x_scale, "sample_float": sample.tolist(), "sample_int8": q_sample.tolist(),
    "sklearn_prediction": log_pred,
    "exported": {"weights_int8": qw.tolist(), "bias_int32": qb},
    "hardware": "Dot product + bias + sign compare", "inference_engine": "logistic_inference.sv"
})

# Decision Tree
tree = DecisionTreeClassifier(max_depth=4, min_samples_leaf=8, random_state=7).fit(X, y)
tree_acc = accuracy_score(y, tree.predict(X))
tree_pred = int(tree.predict(sample.reshape(1, -1))[0])
t = tree.tree_

def tree_expr(node):
    if t.children_left[node] == t.children_right[node]:
        return f"1'b{int(np.argmax(t.value[node][0]))}"
    feat = int(t.feature[node])
    thr_q = int(round(float(t.threshold[node]) / x_scale))
    left = tree_expr(t.children_left[node])
    right = tree_expr(t.children_right[node])
    return f"(($signed(x{feat}) <= {sv_int8(thr_q)}) ? {left} : {right})"

sv = sv_header("decision_tree") + f"""module decision_tree_inference(
 input logic signed [7:0] x0,x1,x2,x3,
 output logic prediction
);
 always_comb prediction = {tree_expr(0)};
endmodule
"""
(GEN / "decision_tree_inference.sv").write_text(sv)
(GEN / "decision_tree_tb.sv").write_text(make_tb("decision_tree_inference", tree_pred, q_sample))
nodes = []
for i in range(t.node_count):
    leaf = t.children_left[i] == t.children_right[i]
    nodes.append({
        "id": i, "leaf": bool(leaf),
        "feature": None if leaf else int(t.feature[i]),
        "threshold_int8": None if leaf else int(round(float(t.threshold[i]) / x_scale)),
        "left": None if leaf else int(t.children_left[i]),
        "right": None if leaf else int(t.children_right[i]),
        "class": int(np.argmax(t.value[i][0])) if leaf else None,
    })
write_json("decision_tree", {
    "model": "DecisionTreeClassifier", "train_accuracy": float(tree_acc),
    "input_scale": x_scale, "sample_float": sample.tolist(), "sample_int8": q_sample.tolist(),
    "sklearn_prediction": tree_pred, "exported": {"nodes": nodes},
    "hardware": "Threshold compare + branch", "inference_engine": "decision_tree_inference.sv"
})

# Random Forest
forest = RandomForestClassifier(
    n_estimators=5, max_depth=4, min_samples_leaf=8, random_state=7
).fit(X, y)
forest_acc = accuracy_score(y, forest.predict(X))
forest_pred = int(forest.predict(sample.reshape(1, -1))[0])

def tree_expr_obj(est, node=0):
    tt = est.tree_
    if tt.children_left[node] == tt.children_right[node]:
        return f"1'b{int(np.argmax(tt.value[node][0]))}"
    feat = int(tt.feature[node])
    thr_q = int(round(float(tt.threshold[node]) / x_scale))
    return f"(($signed(x{feat}) <= {sv_int8(thr_q)}) ? {tree_expr_obj(est, tt.children_left[node])} : {tree_expr_obj(est, tt.children_right[node])})"

votes = [f"vote{i}" for i in range(len(forest.estimators_))]
body = "\n".join(f"  always_comb {votes[i]} = {tree_expr_obj(est)};" for i, est in enumerate(forest.estimators_))
sv = sv_header("random_forest") + f"""module random_forest_inference(
 input logic signed [7:0] x0,x1,x2,x3,
 output logic prediction
);
 logic {', '.join(votes)};
{body}
 integer votes_for_1;
 always_comb begin
   votes_for_1 = {' + '.join(votes)};
   prediction = (votes_for_1 >= 3);
 end
endmodule
"""
(GEN / "random_forest_inference.sv").write_text(sv)
(GEN / "random_forest_tb.sv").write_text(make_tb("random_forest_inference", forest_pred, q_sample))
write_json("random_forest", {
    "model": "RandomForestClassifier", "train_accuracy": float(forest_acc),
    "input_scale": x_scale, "sample_float": sample.tolist(), "sample_int8": q_sample.tolist(),
    "sklearn_prediction": forest_pred, "exported": {"n_trees": 5, "max_depth": 4},
    "hardware": "5 tree engines + majority voting", "inference_engine": "random_forest_inference.sv"
})

# MLP 4 -> 6 ReLU -> 1
mlp = MLPClassifier(
    hidden_layer_sizes=(6,), activation="relu", solver="adam",
    max_iter=2500, random_state=7
).fit(X, y)
mlp_acc = accuracy_score(y, mlp.predict(X))
mlp_pred = int(mlp.predict(sample.reshape(1, -1))[0])
W1 = mlp.coefs_[0]
b1 = mlp.intercepts_[0]
W2 = mlp.coefs_[1][:, 0]
b2 = float(mlp.intercepts_[1][0])
w1_scale = max(float(np.max(np.abs(W1))) / 90.0, 1e-9)
qW1 = np.clip(np.round(W1 / w1_scale), -127, 127).astype(int)
qb1 = np.round(b1 / (x_scale * w1_scale)).astype(int)
hacc = QX @ qW1 + qb1
relu = np.maximum(hacc, 0)
max_relu = max(int(np.max(relu)), 1)
shift = max(0, int(np.ceil(np.log2(max_relu / 100.0)))) if max_relu > 100 else 0
h_scale = x_scale * w1_scale * (2 ** shift)
w2_scale = max(float(np.max(np.abs(W2))) / 90.0, 1e-9)
qW2 = np.clip(np.round(W2 / w2_scale), -127, 127).astype(int)
qb2 = int(round(b2 / (h_scale * w2_scale)))
lines = []
for j in range(6):
    terms = " + ".join(f"$signed(x{i}) * {sv_i32(qW1[i, j])}" for i in range(4))
    lines.append(f"    h{j}_acc = {terms} + {sv_i32(qb1[j])};")
    lines.append(f"    h{j} = (h{j}_acc > 0) ? (h{j}_acc >>> {shift}) : 0;")
out_terms = " + ".join(f"h{j} * {sv_i32(qW2[j])}" for j in range(6))
sv = sv_header("mlp_classifier") + """module mlp_inference(
 input logic signed [7:0] x0,x1,x2,x3,
 output logic prediction
);
"""
for j in range(6):
    sv += f" logic signed [31:0] h{j}_acc; logic signed [31:0] h{j};\n"
sv += " logic signed [31:0] out_score;\n always_comb begin\n"
sv += "\n".join(lines)
sv += f"\n    out_score = {out_terms} + {sv_i32(qb2)};\n    prediction = (out_score >= 0);\n end\nendmodule\n"
(GEN / "mlp_inference.sv").write_text(sv)
(GEN / "mlp_tb.sv").write_text(make_tb("mlp_inference", mlp_pred, q_sample))
h = []
for j in range(6):
    a = int(np.dot(q_sample, qW1[:, j]) + qb1[j])
    h.append(max(0, a) >> shift)
qscore = int(np.dot(np.array(h), qW2) + qb2)
qpred = int(qscore >= 0)
write_json("mlp_classifier", {
    "model": "MLPClassifier", "train_accuracy": float(mlp_acc),
    "input_scale": x_scale, "sample_float": sample.tolist(), "sample_int8": q_sample.tolist(),
    "sklearn_prediction": mlp_pred, "quantized_prediction": qpred,
    "exported": {
        "architecture": "4 -> 6 ReLU -> 1", "w1_int8": qW1.tolist(),
        "b1_int32": qb1.tolist(), "hidden_shift": shift,
        "w2_int8": qW2.tolist(), "b2_int32": qb2,
    },
    "hardware": "Matrix multiply + ReLU + output dot product", "inference_engine": "mlp_inference.sv"
})

summary = {
    "dataset": "Synthetic binary classification (800 rows, 4 features)",
    "models": {
        "logistic_regression": {"accuracy": float(log_acc), "sklearn_prediction": log_pred},
        "decision_tree": {"accuracy": float(tree_acc), "sklearn_prediction": tree_pred},
        "random_forest": {"accuracy": float(forest_acc), "sklearn_prediction": forest_pred},
        "mlp_classifier": {"accuracy": float(mlp_acc), "sklearn_prediction": mlp_pred, "quantized_prediction": qpred},
    },
}
(OUT / "models_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
print(json.dumps(summary, indent=2))
print("Generated SystemVerilog inference engines in generated/")
